fix: email regex local part too long
- causing
MongoServerError: WiredTigerIndex::
insert: key too large to index, failing
1191 { : "~r?9nSBl?!R`TGAD+l2ac|SPKLpn-.=zm8#s/|+gfYQwF/S^KPofy
#SN7k{18CU=q#$b_H#OB}bOe%e{p|{d?`b{I|@wGfketG77sKZJU9oSDZZSSRNE0
Wgbe0fP2D64y3w429f0BOuyPnNpkuRi.r..." }